// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: center_cluster.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "center_cluster.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace libevrpc {

namespace {

const ::google::protobuf::Descriptor* RpcClusterServer_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RpcClusterServer_reflection_ = NULL;
const ::google::protobuf::Descriptor* CenterResponseCluster_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CenterResponseCluster_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* ClusteAction_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ResponseClusterAction_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_center_5fcluster_2eproto() {
  protobuf_AddDesc_center_5fcluster_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "center_cluster.proto");
  GOOGLE_CHECK(file != NULL);
  RpcClusterServer_descriptor_ = file->message_type(0);
  static const int RpcClusterServer_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcClusterServer, cluster_action_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcClusterServer, cluster_server_addr_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcClusterServer, load_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcClusterServer, cpu_used_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcClusterServer, connection_num_),
  };
  RpcClusterServer_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RpcClusterServer_descriptor_,
      RpcClusterServer::default_instance_,
      RpcClusterServer_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcClusterServer, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcClusterServer, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RpcClusterServer));
  CenterResponseCluster_descriptor_ = file->message_type(1);
  static const int CenterResponseCluster_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CenterResponseCluster, center_response_action_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CenterResponseCluster, should_reporter_center_),
  };
  CenterResponseCluster_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CenterResponseCluster_descriptor_,
      CenterResponseCluster::default_instance_,
      CenterResponseCluster_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CenterResponseCluster, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CenterResponseCluster, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CenterResponseCluster));
  ClusteAction_descriptor_ = file->enum_type(0);
  ResponseClusterAction_descriptor_ = file->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_center_5fcluster_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RpcClusterServer_descriptor_, &RpcClusterServer::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CenterResponseCluster_descriptor_, &CenterResponseCluster::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_center_5fcluster_2eproto() {
  delete RpcClusterServer::default_instance_;
  delete RpcClusterServer_reflection_;
  delete CenterResponseCluster::default_instance_;
  delete CenterResponseCluster_reflection_;
}

void protobuf_AddDesc_center_5fcluster_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::libevrpc::protobuf_AddDesc_center_5ftype_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024center_cluster.proto\022\010libevrpc\032\021center"
    "_type.proto\"\227\001\n\020RpcClusterServer\022.\n\016clus"
    "ter_action\030\001 \001(\0162\026.libevrpc.ClusteAction"
    "\022\033\n\023cluster_server_addr\030\002 \001(\t\022\014\n\004load\030\003 "
    "\001(\r\022\020\n\010cpu_used\030\004 \001(\002\022\026\n\016connection_num\030"
    "\005 \001(\005\"x\n\025CenterResponseCluster\022\?\n\026center"
    "_response_action\030\001 \001(\0162\037.libevrpc.Respon"
    "seClusterAction\022\036\n\026should_reporter_cente"
    "r\030\002 \003(\t*.\n\014ClusteAction\022\014\n\010REGISTER\020\001\022\020\n"
    "\014CLUSTER_PING\020\002*\?\n\025ResponseClusterAction"
    "\022\020\n\014CLUSTER_RESP\020\001\022\024\n\020CENTER_NOT_READY\020\002", 440);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "center_cluster.proto", &protobuf_RegisterTypes);
  RpcClusterServer::default_instance_ = new RpcClusterServer();
  CenterResponseCluster::default_instance_ = new CenterResponseCluster();
  RpcClusterServer::default_instance_->InitAsDefaultInstance();
  CenterResponseCluster::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_center_5fcluster_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_center_5fcluster_2eproto {
  StaticDescriptorInitializer_center_5fcluster_2eproto() {
    protobuf_AddDesc_center_5fcluster_2eproto();
  }
} static_descriptor_initializer_center_5fcluster_2eproto_;
const ::google::protobuf::EnumDescriptor* ClusteAction_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClusteAction_descriptor_;
}
bool ClusteAction_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ResponseClusterAction_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ResponseClusterAction_descriptor_;
}
bool ResponseClusterAction_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int RpcClusterServer::kClusterActionFieldNumber;
const int RpcClusterServer::kClusterServerAddrFieldNumber;
const int RpcClusterServer::kLoadFieldNumber;
const int RpcClusterServer::kCpuUsedFieldNumber;
const int RpcClusterServer::kConnectionNumFieldNumber;
#endif  // !_MSC_VER

RpcClusterServer::RpcClusterServer()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:libevrpc.RpcClusterServer)
}

void RpcClusterServer::InitAsDefaultInstance() {
}

RpcClusterServer::RpcClusterServer(const RpcClusterServer& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:libevrpc.RpcClusterServer)
}

void RpcClusterServer::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  cluster_action_ = 1;
  cluster_server_addr_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  load_ = 0u;
  cpu_used_ = 0;
  connection_num_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RpcClusterServer::~RpcClusterServer() {
  // @@protoc_insertion_point(destructor:libevrpc.RpcClusterServer)
  SharedDtor();
}

void RpcClusterServer::SharedDtor() {
  if (cluster_server_addr_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete cluster_server_addr_;
  }
  if (this != default_instance_) {
  }
}

void RpcClusterServer::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RpcClusterServer::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RpcClusterServer_descriptor_;
}

const RpcClusterServer& RpcClusterServer::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_center_5fcluster_2eproto();
  return *default_instance_;
}

RpcClusterServer* RpcClusterServer::default_instance_ = NULL;

RpcClusterServer* RpcClusterServer::New() const {
  return new RpcClusterServer;
}

void RpcClusterServer::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<RpcClusterServer*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 31) {
    ZR_(load_, connection_num_);
    cluster_action_ = 1;
    if (has_cluster_server_addr()) {
      if (cluster_server_addr_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        cluster_server_addr_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool RpcClusterServer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:libevrpc.RpcClusterServer)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .libevrpc.ClusteAction cluster_action = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::libevrpc::ClusteAction_IsValid(value)) {
            set_cluster_action(static_cast< ::libevrpc::ClusteAction >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_cluster_server_addr;
        break;
      }

      // optional string cluster_server_addr = 2;
      case 2: {
        if (tag == 18) {
         parse_cluster_server_addr:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cluster_server_addr()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->cluster_server_addr().data(), this->cluster_server_addr().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "cluster_server_addr");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_load;
        break;
      }

      // optional uint32 load = 3;
      case 3: {
        if (tag == 24) {
         parse_load:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &load_)));
          set_has_load();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(37)) goto parse_cpu_used;
        break;
      }

      // optional float cpu_used = 4;
      case 4: {
        if (tag == 37) {
         parse_cpu_used:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &cpu_used_)));
          set_has_cpu_used();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_connection_num;
        break;
      }

      // optional int32 connection_num = 5;
      case 5: {
        if (tag == 40) {
         parse_connection_num:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &connection_num_)));
          set_has_connection_num();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:libevrpc.RpcClusterServer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:libevrpc.RpcClusterServer)
  return false;
#undef DO_
}

void RpcClusterServer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:libevrpc.RpcClusterServer)
  // optional .libevrpc.ClusteAction cluster_action = 1;
  if (has_cluster_action()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->cluster_action(), output);
  }

  // optional string cluster_server_addr = 2;
  if (has_cluster_server_addr()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->cluster_server_addr().data(), this->cluster_server_addr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "cluster_server_addr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->cluster_server_addr(), output);
  }

  // optional uint32 load = 3;
  if (has_load()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->load(), output);
  }

  // optional float cpu_used = 4;
  if (has_cpu_used()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->cpu_used(), output);
  }

  // optional int32 connection_num = 5;
  if (has_connection_num()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->connection_num(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:libevrpc.RpcClusterServer)
}

::google::protobuf::uint8* RpcClusterServer::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:libevrpc.RpcClusterServer)
  // optional .libevrpc.ClusteAction cluster_action = 1;
  if (has_cluster_action()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->cluster_action(), target);
  }

  // optional string cluster_server_addr = 2;
  if (has_cluster_server_addr()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->cluster_server_addr().data(), this->cluster_server_addr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "cluster_server_addr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->cluster_server_addr(), target);
  }

  // optional uint32 load = 3;
  if (has_load()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->load(), target);
  }

  // optional float cpu_used = 4;
  if (has_cpu_used()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->cpu_used(), target);
  }

  // optional int32 connection_num = 5;
  if (has_connection_num()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->connection_num(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:libevrpc.RpcClusterServer)
  return target;
}

int RpcClusterServer::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .libevrpc.ClusteAction cluster_action = 1;
    if (has_cluster_action()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->cluster_action());
    }

    // optional string cluster_server_addr = 2;
    if (has_cluster_server_addr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->cluster_server_addr());
    }

    // optional uint32 load = 3;
    if (has_load()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->load());
    }

    // optional float cpu_used = 4;
    if (has_cpu_used()) {
      total_size += 1 + 4;
    }

    // optional int32 connection_num = 5;
    if (has_connection_num()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->connection_num());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RpcClusterServer::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const RpcClusterServer* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const RpcClusterServer*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void RpcClusterServer::MergeFrom(const RpcClusterServer& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_cluster_action()) {
      set_cluster_action(from.cluster_action());
    }
    if (from.has_cluster_server_addr()) {
      set_cluster_server_addr(from.cluster_server_addr());
    }
    if (from.has_load()) {
      set_load(from.load());
    }
    if (from.has_cpu_used()) {
      set_cpu_used(from.cpu_used());
    }
    if (from.has_connection_num()) {
      set_connection_num(from.connection_num());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void RpcClusterServer::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RpcClusterServer::CopyFrom(const RpcClusterServer& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RpcClusterServer::IsInitialized() const {

  return true;
}

void RpcClusterServer::Swap(RpcClusterServer* other) {
  if (other != this) {
    std::swap(cluster_action_, other->cluster_action_);
    std::swap(cluster_server_addr_, other->cluster_server_addr_);
    std::swap(load_, other->load_);
    std::swap(cpu_used_, other->cpu_used_);
    std::swap(connection_num_, other->connection_num_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata RpcClusterServer::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RpcClusterServer_descriptor_;
  metadata.reflection = RpcClusterServer_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CenterResponseCluster::kCenterResponseActionFieldNumber;
const int CenterResponseCluster::kShouldReporterCenterFieldNumber;
#endif  // !_MSC_VER

CenterResponseCluster::CenterResponseCluster()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:libevrpc.CenterResponseCluster)
}

void CenterResponseCluster::InitAsDefaultInstance() {
}

CenterResponseCluster::CenterResponseCluster(const CenterResponseCluster& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:libevrpc.CenterResponseCluster)
}

void CenterResponseCluster::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  center_response_action_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CenterResponseCluster::~CenterResponseCluster() {
  // @@protoc_insertion_point(destructor:libevrpc.CenterResponseCluster)
  SharedDtor();
}

void CenterResponseCluster::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CenterResponseCluster::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CenterResponseCluster::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CenterResponseCluster_descriptor_;
}

const CenterResponseCluster& CenterResponseCluster::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_center_5fcluster_2eproto();
  return *default_instance_;
}

CenterResponseCluster* CenterResponseCluster::default_instance_ = NULL;

CenterResponseCluster* CenterResponseCluster::New() const {
  return new CenterResponseCluster;
}

void CenterResponseCluster::Clear() {
  center_response_action_ = 1;
  should_reporter_center_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CenterResponseCluster::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:libevrpc.CenterResponseCluster)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .libevrpc.ResponseClusterAction center_response_action = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::libevrpc::ResponseClusterAction_IsValid(value)) {
            set_center_response_action(static_cast< ::libevrpc::ResponseClusterAction >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_should_reporter_center;
        break;
      }

      // repeated string should_reporter_center = 2;
      case 2: {
        if (tag == 18) {
         parse_should_reporter_center:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_should_reporter_center()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->should_reporter_center(this->should_reporter_center_size() - 1).data(),
            this->should_reporter_center(this->should_reporter_center_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "should_reporter_center");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_should_reporter_center;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:libevrpc.CenterResponseCluster)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:libevrpc.CenterResponseCluster)
  return false;
#undef DO_
}

void CenterResponseCluster::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:libevrpc.CenterResponseCluster)
  // optional .libevrpc.ResponseClusterAction center_response_action = 1;
  if (has_center_response_action()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->center_response_action(), output);
  }

  // repeated string should_reporter_center = 2;
  for (int i = 0; i < this->should_reporter_center_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
    this->should_reporter_center(i).data(), this->should_reporter_center(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE,
    "should_reporter_center");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->should_reporter_center(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:libevrpc.CenterResponseCluster)
}

::google::protobuf::uint8* CenterResponseCluster::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:libevrpc.CenterResponseCluster)
  // optional .libevrpc.ResponseClusterAction center_response_action = 1;
  if (has_center_response_action()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->center_response_action(), target);
  }

  // repeated string should_reporter_center = 2;
  for (int i = 0; i < this->should_reporter_center_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->should_reporter_center(i).data(), this->should_reporter_center(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "should_reporter_center");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->should_reporter_center(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:libevrpc.CenterResponseCluster)
  return target;
}

int CenterResponseCluster::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .libevrpc.ResponseClusterAction center_response_action = 1;
    if (has_center_response_action()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->center_response_action());
    }

  }
  // repeated string should_reporter_center = 2;
  total_size += 1 * this->should_reporter_center_size();
  for (int i = 0; i < this->should_reporter_center_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->should_reporter_center(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CenterResponseCluster::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CenterResponseCluster* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CenterResponseCluster*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CenterResponseCluster::MergeFrom(const CenterResponseCluster& from) {
  GOOGLE_CHECK_NE(&from, this);
  should_reporter_center_.MergeFrom(from.should_reporter_center_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_center_response_action()) {
      set_center_response_action(from.center_response_action());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CenterResponseCluster::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CenterResponseCluster::CopyFrom(const CenterResponseCluster& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CenterResponseCluster::IsInitialized() const {

  return true;
}

void CenterResponseCluster::Swap(CenterResponseCluster* other) {
  if (other != this) {
    std::swap(center_response_action_, other->center_response_action_);
    should_reporter_center_.Swap(&other->should_reporter_center_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CenterResponseCluster::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CenterResponseCluster_descriptor_;
  metadata.reflection = CenterResponseCluster_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace libevrpc

// @@protoc_insertion_point(global_scope)
