// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: center_client.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "center_client.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace libevrpc {

namespace {

const ::google::protobuf::Descriptor* ClientWithCenter_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClientWithCenter_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* ClientClusterAction_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_center_5fclient_2eproto() {
  protobuf_AddDesc_center_5fclient_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "center_client.proto");
  GOOGLE_CHECK(file != NULL);
  ClientWithCenter_descriptor_ = file->message_type(0);
  static const int ClientWithCenter_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientWithCenter, from_addr_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientWithCenter, client_center_action_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientWithCenter, should_communicate_center_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientWithCenter, cluster_server_list_),
  };
  ClientWithCenter_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ClientWithCenter_descriptor_,
      ClientWithCenter::default_instance_,
      ClientWithCenter_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientWithCenter, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientWithCenter, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ClientWithCenter));
  ClientClusterAction_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_center_5fclient_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ClientWithCenter_descriptor_, &ClientWithCenter::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_center_5fclient_2eproto() {
  delete ClientWithCenter::default_instance_;
  delete ClientWithCenter_reflection_;
}

void protobuf_AddDesc_center_5fclient_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::libevrpc::protobuf_AddDesc_center_5ftype_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023center_client.proto\022\010libevrpc\032\021center_"
    "type.proto\"\242\001\n\020ClientWithCenter\022\021\n\tfrom_"
    "addr\030\001 \001(\t\022;\n\024client_center_action\030\002 \001(\016"
    "2\035.libevrpc.ClientClusterAction\022!\n\031shoul"
    "d_communicate_center\030\003 \003(\t\022\033\n\023cluster_se"
    "rver_list\030\004 \003(\t*k\n\023ClientClusterAction\022\023"
    "\n\017CLIENT_INIT_REQ\020\001\022\026\n\022UPDATE_SERVER_INF"
    "O\020\002\022\022\n\016CENTER_RESP_OK\020\003\022\023\n\017CENTER_RESP_E"
    "RR\020\004", 324);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "center_client.proto", &protobuf_RegisterTypes);
  ClientWithCenter::default_instance_ = new ClientWithCenter();
  ClientWithCenter::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_center_5fclient_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_center_5fclient_2eproto {
  StaticDescriptorInitializer_center_5fclient_2eproto() {
    protobuf_AddDesc_center_5fclient_2eproto();
  }
} static_descriptor_initializer_center_5fclient_2eproto_;
const ::google::protobuf::EnumDescriptor* ClientClusterAction_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClientClusterAction_descriptor_;
}
bool ClientClusterAction_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int ClientWithCenter::kFromAddrFieldNumber;
const int ClientWithCenter::kClientCenterActionFieldNumber;
const int ClientWithCenter::kShouldCommunicateCenterFieldNumber;
const int ClientWithCenter::kClusterServerListFieldNumber;
#endif  // !_MSC_VER

ClientWithCenter::ClientWithCenter()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:libevrpc.ClientWithCenter)
}

void ClientWithCenter::InitAsDefaultInstance() {
}

ClientWithCenter::ClientWithCenter(const ClientWithCenter& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:libevrpc.ClientWithCenter)
}

void ClientWithCenter::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  from_addr_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  client_center_action_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ClientWithCenter::~ClientWithCenter() {
  // @@protoc_insertion_point(destructor:libevrpc.ClientWithCenter)
  SharedDtor();
}

void ClientWithCenter::SharedDtor() {
  if (from_addr_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete from_addr_;
  }
  if (this != default_instance_) {
  }
}

void ClientWithCenter::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientWithCenter::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClientWithCenter_descriptor_;
}

const ClientWithCenter& ClientWithCenter::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_center_5fclient_2eproto();
  return *default_instance_;
}

ClientWithCenter* ClientWithCenter::default_instance_ = NULL;

ClientWithCenter* ClientWithCenter::New() const {
  return new ClientWithCenter;
}

void ClientWithCenter::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_from_addr()) {
      if (from_addr_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        from_addr_->clear();
      }
    }
    client_center_action_ = 1;
  }
  should_communicate_center_.Clear();
  cluster_server_list_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ClientWithCenter::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:libevrpc.ClientWithCenter)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string from_addr = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_from_addr()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->from_addr().data(), this->from_addr().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "from_addr");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_client_center_action;
        break;
      }

      // optional .libevrpc.ClientClusterAction client_center_action = 2;
      case 2: {
        if (tag == 16) {
         parse_client_center_action:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::libevrpc::ClientClusterAction_IsValid(value)) {
            set_client_center_action(static_cast< ::libevrpc::ClientClusterAction >(value));
          } else {
            mutable_unknown_fields()->AddVarint(2, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_should_communicate_center;
        break;
      }

      // repeated string should_communicate_center = 3;
      case 3: {
        if (tag == 26) {
         parse_should_communicate_center:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_should_communicate_center()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->should_communicate_center(this->should_communicate_center_size() - 1).data(),
            this->should_communicate_center(this->should_communicate_center_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "should_communicate_center");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_should_communicate_center;
        if (input->ExpectTag(34)) goto parse_cluster_server_list;
        break;
      }

      // repeated string cluster_server_list = 4;
      case 4: {
        if (tag == 34) {
         parse_cluster_server_list:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_cluster_server_list()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->cluster_server_list(this->cluster_server_list_size() - 1).data(),
            this->cluster_server_list(this->cluster_server_list_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "cluster_server_list");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_cluster_server_list;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:libevrpc.ClientWithCenter)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:libevrpc.ClientWithCenter)
  return false;
#undef DO_
}

void ClientWithCenter::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:libevrpc.ClientWithCenter)
  // optional string from_addr = 1;
  if (has_from_addr()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->from_addr().data(), this->from_addr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "from_addr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->from_addr(), output);
  }

  // optional .libevrpc.ClientClusterAction client_center_action = 2;
  if (has_client_center_action()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->client_center_action(), output);
  }

  // repeated string should_communicate_center = 3;
  for (int i = 0; i < this->should_communicate_center_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
    this->should_communicate_center(i).data(), this->should_communicate_center(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE,
    "should_communicate_center");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->should_communicate_center(i), output);
  }

  // repeated string cluster_server_list = 4;
  for (int i = 0; i < this->cluster_server_list_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
    this->cluster_server_list(i).data(), this->cluster_server_list(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE,
    "cluster_server_list");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->cluster_server_list(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:libevrpc.ClientWithCenter)
}

::google::protobuf::uint8* ClientWithCenter::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:libevrpc.ClientWithCenter)
  // optional string from_addr = 1;
  if (has_from_addr()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->from_addr().data(), this->from_addr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "from_addr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->from_addr(), target);
  }

  // optional .libevrpc.ClientClusterAction client_center_action = 2;
  if (has_client_center_action()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->client_center_action(), target);
  }

  // repeated string should_communicate_center = 3;
  for (int i = 0; i < this->should_communicate_center_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->should_communicate_center(i).data(), this->should_communicate_center(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "should_communicate_center");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->should_communicate_center(i), target);
  }

  // repeated string cluster_server_list = 4;
  for (int i = 0; i < this->cluster_server_list_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->cluster_server_list(i).data(), this->cluster_server_list(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "cluster_server_list");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(4, this->cluster_server_list(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:libevrpc.ClientWithCenter)
  return target;
}

int ClientWithCenter::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string from_addr = 1;
    if (has_from_addr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->from_addr());
    }

    // optional .libevrpc.ClientClusterAction client_center_action = 2;
    if (has_client_center_action()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->client_center_action());
    }

  }
  // repeated string should_communicate_center = 3;
  total_size += 1 * this->should_communicate_center_size();
  for (int i = 0; i < this->should_communicate_center_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->should_communicate_center(i));
  }

  // repeated string cluster_server_list = 4;
  total_size += 1 * this->cluster_server_list_size();
  for (int i = 0; i < this->cluster_server_list_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->cluster_server_list(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClientWithCenter::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ClientWithCenter* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ClientWithCenter*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ClientWithCenter::MergeFrom(const ClientWithCenter& from) {
  GOOGLE_CHECK_NE(&from, this);
  should_communicate_center_.MergeFrom(from.should_communicate_center_);
  cluster_server_list_.MergeFrom(from.cluster_server_list_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_from_addr()) {
      set_from_addr(from.from_addr());
    }
    if (from.has_client_center_action()) {
      set_client_center_action(from.client_center_action());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ClientWithCenter::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientWithCenter::CopyFrom(const ClientWithCenter& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientWithCenter::IsInitialized() const {

  return true;
}

void ClientWithCenter::Swap(ClientWithCenter* other) {
  if (other != this) {
    std::swap(from_addr_, other->from_addr_);
    std::swap(client_center_action_, other->client_center_action_);
    should_communicate_center_.Swap(&other->should_communicate_center_);
    cluster_server_list_.Swap(&other->cluster_server_list_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ClientWithCenter::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClientWithCenter_descriptor_;
  metadata.reflection = ClientWithCenter_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace libevrpc

// @@protoc_insertion_point(global_scope)
