// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: center_cluster.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "center_cluster.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace libevrpc {

namespace {

const ::google::protobuf::Descriptor* CenterCluster_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CenterCluster_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_center_5fcluster_2eproto() {
  protobuf_AddDesc_center_5fcluster_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "center_cluster.proto");
  GOOGLE_CHECK(file != NULL);
  CenterCluster_descriptor_ = file->message_type(0);
  static const int CenterCluster_offsets_[1] = {
  };
  CenterCluster_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CenterCluster_descriptor_,
      CenterCluster::default_instance_,
      CenterCluster_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CenterCluster, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CenterCluster, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CenterCluster));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_center_5fcluster_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CenterCluster_descriptor_, &CenterCluster::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_center_5fcluster_2eproto() {
  delete CenterCluster::default_instance_;
  delete CenterCluster_reflection_;
}

void protobuf_AddDesc_center_5fcluster_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::libevrpc::protobuf_AddDesc_center_5ftype_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024center_cluster.proto\022\010libevrpc\032\021center"
    "_type.proto\"\017\n\rCenterCluster", 68);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "center_cluster.proto", &protobuf_RegisterTypes);
  CenterCluster::default_instance_ = new CenterCluster();
  CenterCluster::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_center_5fcluster_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_center_5fcluster_2eproto {
  StaticDescriptorInitializer_center_5fcluster_2eproto() {
    protobuf_AddDesc_center_5fcluster_2eproto();
  }
} static_descriptor_initializer_center_5fcluster_2eproto_;

// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

CenterCluster::CenterCluster()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:libevrpc.CenterCluster)
}

void CenterCluster::InitAsDefaultInstance() {
}

CenterCluster::CenterCluster(const CenterCluster& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:libevrpc.CenterCluster)
}

void CenterCluster::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CenterCluster::~CenterCluster() {
  // @@protoc_insertion_point(destructor:libevrpc.CenterCluster)
  SharedDtor();
}

void CenterCluster::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CenterCluster::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CenterCluster::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CenterCluster_descriptor_;
}

const CenterCluster& CenterCluster::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_center_5fcluster_2eproto();
  return *default_instance_;
}

CenterCluster* CenterCluster::default_instance_ = NULL;

CenterCluster* CenterCluster::New() const {
  return new CenterCluster;
}

void CenterCluster::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CenterCluster::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:libevrpc.CenterCluster)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:libevrpc.CenterCluster)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:libevrpc.CenterCluster)
  return false;
#undef DO_
}

void CenterCluster::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:libevrpc.CenterCluster)
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:libevrpc.CenterCluster)
}

::google::protobuf::uint8* CenterCluster::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:libevrpc.CenterCluster)
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:libevrpc.CenterCluster)
  return target;
}

int CenterCluster::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CenterCluster::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CenterCluster* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CenterCluster*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CenterCluster::MergeFrom(const CenterCluster& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CenterCluster::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CenterCluster::CopyFrom(const CenterCluster& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CenterCluster::IsInitialized() const {

  return true;
}

void CenterCluster::Swap(CenterCluster* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CenterCluster::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CenterCluster_descriptor_;
  metadata.reflection = CenterCluster_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace libevrpc

// @@protoc_insertion_point(global_scope)
