// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: center_client.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "center_client.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace libevrpc {

namespace {

const ::google::protobuf::Descriptor* CenterResponseClient_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CenterResponseClient_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* ResponseClientAction_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_center_5fclient_2eproto() {
  protobuf_AddDesc_center_5fclient_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "center_client.proto");
  GOOGLE_CHECK(file != NULL);
  CenterResponseClient_descriptor_ = file->message_type(0);
  static const int CenterResponseClient_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CenterResponseClient, response_client_action_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CenterResponseClient, should_communicate_center_),
  };
  CenterResponseClient_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CenterResponseClient_descriptor_,
      CenterResponseClient::default_instance_,
      CenterResponseClient_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CenterResponseClient, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CenterResponseClient, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CenterResponseClient));
  ResponseClientAction_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_center_5fclient_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CenterResponseClient_descriptor_, &CenterResponseClient::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_center_5fclient_2eproto() {
  delete CenterResponseClient::default_instance_;
  delete CenterResponseClient_reflection_;
}

void protobuf_AddDesc_center_5fclient_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::libevrpc::protobuf_AddDesc_center_5ftype_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023center_client.proto\022\010libevrpc\032\021center_"
    "type.proto\"y\n\024CenterResponseClient\022>\n\026re"
    "sponse_client_action\030\001 \001(\0162\036.libevrpc.Re"
    "sponseClientAction\022!\n\031should_communicate"
    "_center\030\002 \003(\t*\'\n\024ResponseClientAction\022\017\n"
    "\013CLIENT_RESP\020\001", 214);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "center_client.proto", &protobuf_RegisterTypes);
  CenterResponseClient::default_instance_ = new CenterResponseClient();
  CenterResponseClient::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_center_5fclient_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_center_5fclient_2eproto {
  StaticDescriptorInitializer_center_5fclient_2eproto() {
    protobuf_AddDesc_center_5fclient_2eproto();
  }
} static_descriptor_initializer_center_5fclient_2eproto_;
const ::google::protobuf::EnumDescriptor* ResponseClientAction_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ResponseClientAction_descriptor_;
}
bool ResponseClientAction_IsValid(int value) {
  switch(value) {
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int CenterResponseClient::kResponseClientActionFieldNumber;
const int CenterResponseClient::kShouldCommunicateCenterFieldNumber;
#endif  // !_MSC_VER

CenterResponseClient::CenterResponseClient()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:libevrpc.CenterResponseClient)
}

void CenterResponseClient::InitAsDefaultInstance() {
}

CenterResponseClient::CenterResponseClient(const CenterResponseClient& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:libevrpc.CenterResponseClient)
}

void CenterResponseClient::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  response_client_action_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CenterResponseClient::~CenterResponseClient() {
  // @@protoc_insertion_point(destructor:libevrpc.CenterResponseClient)
  SharedDtor();
}

void CenterResponseClient::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CenterResponseClient::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CenterResponseClient::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CenterResponseClient_descriptor_;
}

const CenterResponseClient& CenterResponseClient::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_center_5fclient_2eproto();
  return *default_instance_;
}

CenterResponseClient* CenterResponseClient::default_instance_ = NULL;

CenterResponseClient* CenterResponseClient::New() const {
  return new CenterResponseClient;
}

void CenterResponseClient::Clear() {
  response_client_action_ = 1;
  should_communicate_center_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CenterResponseClient::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:libevrpc.CenterResponseClient)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .libevrpc.ResponseClientAction response_client_action = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::libevrpc::ResponseClientAction_IsValid(value)) {
            set_response_client_action(static_cast< ::libevrpc::ResponseClientAction >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_should_communicate_center;
        break;
      }

      // repeated string should_communicate_center = 2;
      case 2: {
        if (tag == 18) {
         parse_should_communicate_center:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_should_communicate_center()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->should_communicate_center(this->should_communicate_center_size() - 1).data(),
            this->should_communicate_center(this->should_communicate_center_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "should_communicate_center");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_should_communicate_center;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:libevrpc.CenterResponseClient)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:libevrpc.CenterResponseClient)
  return false;
#undef DO_
}

void CenterResponseClient::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:libevrpc.CenterResponseClient)
  // optional .libevrpc.ResponseClientAction response_client_action = 1;
  if (has_response_client_action()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->response_client_action(), output);
  }

  // repeated string should_communicate_center = 2;
  for (int i = 0; i < this->should_communicate_center_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
    this->should_communicate_center(i).data(), this->should_communicate_center(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE,
    "should_communicate_center");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->should_communicate_center(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:libevrpc.CenterResponseClient)
}

::google::protobuf::uint8* CenterResponseClient::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:libevrpc.CenterResponseClient)
  // optional .libevrpc.ResponseClientAction response_client_action = 1;
  if (has_response_client_action()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->response_client_action(), target);
  }

  // repeated string should_communicate_center = 2;
  for (int i = 0; i < this->should_communicate_center_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->should_communicate_center(i).data(), this->should_communicate_center(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "should_communicate_center");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->should_communicate_center(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:libevrpc.CenterResponseClient)
  return target;
}

int CenterResponseClient::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .libevrpc.ResponseClientAction response_client_action = 1;
    if (has_response_client_action()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->response_client_action());
    }

  }
  // repeated string should_communicate_center = 2;
  total_size += 1 * this->should_communicate_center_size();
  for (int i = 0; i < this->should_communicate_center_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->should_communicate_center(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CenterResponseClient::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CenterResponseClient* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CenterResponseClient*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CenterResponseClient::MergeFrom(const CenterResponseClient& from) {
  GOOGLE_CHECK_NE(&from, this);
  should_communicate_center_.MergeFrom(from.should_communicate_center_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_response_client_action()) {
      set_response_client_action(from.response_client_action());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CenterResponseClient::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CenterResponseClient::CopyFrom(const CenterResponseClient& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CenterResponseClient::IsInitialized() const {

  return true;
}

void CenterResponseClient::Swap(CenterResponseClient* other) {
  if (other != this) {
    std::swap(response_client_action_, other->response_client_action_);
    should_communicate_center_.Swap(&other->should_communicate_center_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CenterResponseClient::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CenterResponseClient_descriptor_;
  metadata.reflection = CenterResponseClient_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace libevrpc

// @@protoc_insertion_point(global_scope)
